In [1]:
#import pandas
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r"C:\Users\Raghavendra N\OneDrive\Official\Datasets\ML Datasets\bmi_diabetes.csv")

In [3]:
data.head()

bmi  label
0  33.6      1
1  26.6      0
2  23.3      1
3  28.1      0
4  43.1      1

In [4]:
data.label.value_counts(normalize=True)

0    0.651042
1    0.348958
Name: label, dtype: float64

In [5]:
#Extracting the feature into X
X = data[['bmi']].values
#Extracting the target into y
y=data['label'].values

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,
                                               random_state=4, stratify = y)

In [7]:
n_train = len(y_train)
n_test = len(y_test)

In [8]:
#In my training set finding the proportion of 0's and 1's
print(len(y_train[y_train==0])/n_train)
print(len(y_train[y_train==1])/n_train)

0.6510416666666666
0.3489583333333333


In [9]:
#In my training set finding the proportion of 0's and 1's
print(len(y_test[y_test==0])/n_test)
print(len(y_test[y_test==1])/n_test)

0.6510416666666666
0.3489583333333333


 - if the Stratify argument is set to the class labels in the train_test_split, it will ensure that both the training and the test samples will have the same proportion of both the target classes
 - With imbalanced classes, its recommended to create stratified random samples

In [10]:
# import the class
from sklearn.linear_model import LogisticRegression

In [11]:
# instantiate the model (using the default parameters)
logreg = LogisticRegression()

In [12]:
# fit the model with data
logreg.fit(X_train,y_train)

LogisticRegression()

In [13]:
#Predict on the test Dataset
y_pred=logreg.predict(X_test)

In [14]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test,y_pred)
print(accuracy)

0.6302083333333334


In [15]:
logreg.predict_proba(X_test)[:10]

array([[0.78619742, 0.21380258],
       [0.49307678, 0.50692322],
       [0.36652191, 0.63347809],
       [0.66114445, 0.33885555],
       [0.71245877, 0.28754123],
       [0.76636006, 0.23363994],
       [0.61562016, 0.38437984],
       [0.70387059, 0.29612941],
       [0.76073304, 0.23926696],
       [0.79816761, 0.20183239]])

In [16]:
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[107,  18],
       [ 53,  14]], dtype=int64)

In [17]:
#Predictions For a BMI value of 45
print(logreg.predict([[45]]))
logreg.predict_proba([[45]])

[1]


array([[0.34275035, 0.65724965]])

In [18]:
#Predictions For a BMI value of 25
print(logreg.predict([[25]]))
logreg.predict_proba([[25]])

[0]


array([[0.80640664, 0.19359336]])